require("maxime.packer")
require('maxime.set')
require('maxime.lspzero')
-- require("maxime.lsp")
-- require('maxime.luasnip')
-- require("maxime.cmp")
require("maxime.dap")
-- require("maxime.treesitter")
require("maxime.git")
